import { getServerLangByCookie } from '@/features/lang/server/get-server-lang-by-cookie';
import { Footer } from '@/features/layout/ui/footer';
import { AppConfigProvider } from '@/providers/app-config-provider';
import type { Metadata } from 'next';
import { headers } from 'next/headers';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers();
  const userAgent = headersList.get('user-agent');
  const lang = await getServerLangByCookie();

  return (
    <html lang="en">
      <body>
        <AppConfigProvider lang={lang} userAgent={userAgent || ''}>
          <nav>
            <Link prefetch={false} href="/">
              HOME
            </Link>{' '}
            &nbsp;
            <Link prefetch={false} href="/about">
              ABOUT
            </Link>{' '}
            &nbsp;
          </nav>
          <div>{children}</div>
          <Footer />
        </AppConfigProvider>
      </body>
    </html>
  );
}
