import { Footer } from '@/features/layout/ui/footer';
import { AppConfigProvider } from '@/providers/app-config-provider';
import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';
import { headers } from 'next/headers';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers();
  const userAgent = headersList.get('user-agent');
  const i18nMessages = await getMessages();
  const i18nLocale = await getLocale();

  return (
    <html lang={i18nLocale}>
      <body>
        <NextIntlClientProvider messages={i18nMessages}>
          <AppConfigProvider userAgent={userAgent || ''}>
            <nav>
              <Link prefetch={false} href="/">
                HOME
              </Link>{' '}
              &nbsp;
              <Link prefetch={false} href="/about">
                ABOUT
              </Link>{' '}
              &nbsp;
            </nav>
            <div>{children}</div>
            <Footer />
          </AppConfigProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
